name: fhir_at_rest
description: This package builds on the basic FHIR package. It allows easy
  creation of RESTful calls to a FHIR server or FHIR API.
version: 0.5.0-2
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_at_rest

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  fhir:
    git:
      url: https://github.com/i-atros/fhir.git
      path: fhir
  freezed_annotation: ^2.4.4
  http: ^1.1.0
  json_annotation: 4.9.0

dev_dependencies:
  build_runner: ^2.4.14
  freezed: ^3.0.0-0.0.dev
  test: ^1.21.0